Exove/local-docker

ld.sh
Fix is_dockersync() test and add quotes to variables in tests where they were missing in ld.sh
=> Fix is dockersync

docker/build/php/7.2/conf.d/95-drupal-development.ini, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/docker-sync.common.yml, docker/docker-sync.skeleton.yml
Add some revised volumes (folder shares) and only-as-reference template file (`docker/docker-compose.nfs.yml`) for using NFS mounts with Docker.
=> Imporve volumes and syncs

.env.example, docker/build/php/7.1/conf.d/95-drupal-development.ini, docker/build/php/7.2/conf.d/95-drupal-development.ini, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, ld.sh
Ensure we do have a .env file, handle the creation (copy from .env.example during init) and use the values in some places.
=> Add env file and handling

ld.sh
Modified from the 'composer' shortcut.
=> Add ld shortcut 'drush'

.env.example
=> Issue 7 by rpsu: Prevent composer complaining about running as root

.editorconfig
Fixes #23 except the .gitattributes file is not here - probably not that necessary as of now.
=> Git and editor config files

ld.sh
Clarify notation when using function to get a status for "are we using docker-sync here".
Fix leftover .yml file removing so that it actually removes the leftover files.
=> Simplify function usage

ld.sh
Fix function return value. Ensure APP root folder exists prior booting up Docker-sync (to avoid ugly error messages in shell).
=> Fix function return value

docker/scripts/ld.colors.sh, ld.sh
Bring some colors to the shell output. Inital, ideating -level.
Colors and font weight variations borrowed from https://stackoverflow.com/a/28938235
=> Use colored output in shell - initial testing here

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
=> Remove unnecessary exposed port from Mailhog, use sync folder w/ NodeJS

ld.sh
IDE can track now included files, and auto-complete variables etc.
nice DX thinges.
=> Remvoe full path from commands

README.md
=> Adding info about ports configuration to README.md

README.md
=> Add xdebug command info to README.me

.env.example, README.md
Clarify README.md and `.env.example` variable grouping
=> Refactor env vars introduction

docker/scripts/ld.command.self-update.sh, ld.sh
Add a command to allow updating local-docker itself to a specifig version. TAG is required.
=> Add self-udpate command to ld

docker/scripts/ld.command.configure-network.sh
=> Issue 64: Add all subdomains to /etc/hosts file along w/ the main one

docker/scripts/ld.command.run-tests.sh
=> Issue 71: Add run-tests -command

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
=> Issue 77: Disable composer container

docker/scripts/ld.command.composer.sh, docker/scripts/ld.command.drupal-files-folder-perms.sh, docker/scripts/ld.command.drupal-structure-fix.sh, docker/scripts/ld.command.drush.sh, docker/scripts/ld.command.dump.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.restore.sh, docker/scripts/ld.command.run-tests.sh, docker/scripts/ld.command.up.sh, docker/scripts/ld.command.xdebug.sh, docker/scripts/ld.functions.sh, ld.sh
Refactor functions and their return values and handing of exceptions.
=> Issue 54 function return values

README.md
The previous description of traefik was copy-paste from the adminer entry. I'm not sure I caught the best wording here but improvements welcome!
=> Improve description of traefik in Readme

docker/scripts/ld.command.dump.sh, docker/scripts/ld.command.restore.sh, docker/scripts/ld.command.up.sh, docker/scripts/ld.functions.sh, ld.sh
* Refactor VARIABLE introducing (offload to command files, remove in the main file).
* Start DB container for database dumps if it is not running
=> Improve db operations

docker/scripts/release.sh, ld.sh
This script should be used only on `master` branch, and from project root.
`$ docker/scripts/release.sh TAG`
=> Add script to create relases

docker/scripts/release.sh
=> Fix typo in shell scipt test

docker/scripts/ld.command.self-update.sh, docker/scripts/self-update.sh
Updating shell script itself seems to lead to various runtime issues (script is read on the fly, line by line?)
=> Move self-update to a separate script, outside ld

docker/scripts/ld.command.restore.sh
=> Typo fixes in restore script

docker/scripts/ld.functions.sh
Fixing platform specifities and bash `test` problems in the `required_binaries_check` function. 
See https://github.com/Exove/local-docker/commit/2610a49542067df79c1a7f9fe065e7954f023de9/checks?check_suite_id=311310004 for errors regarding this, for example.
=> Fix required binaries check

.env.example
Corrected typos and the most convoluted sentence structures.
=> Proofread .env.example

docker/scripts/ld.command.stop.sh
The instruction text was inaccurate, seemed like a copy-paste from ld_command_down_help().
The correction is based on what the comments in this file's exec() command say.
---
=> Correct ld_command_stop_help

.env.example, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh, docker/scripts/ld.functions.sh, ld.sh
- Re-use already given values
- Create config files in a more sane way
- Remove default values in some variables from .env.example to not trip into them during init.
=> Improve init wizard, re-use values for defaults

docker/scripts/ld.command.db-backup.sh, docker/scripts/ld.command.db-dump.sh, docker/scripts/ld.command.db-import.sh, docker/scripts/ld.command.db-restore.sh, docker/scripts/ld.command.init.sh
Fixes db-import, db-dump and db-backup commands.
=> Fix broken funciton names and SQL commads

docker/scripts/ld.command.containers.sh, docker/scripts/ld.command.info.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.functions.sh, ld.sh
Fixes #114 
Adds 2 commands and slightly better config-import/create handling.
=> Issue 114 add info running commands

docker/scripts/ld.command.db-backup.sh, docker/scripts/ld.command.db-dump.sh, docker/scripts/ld.command.db-import.sh, docker/scripts/ld.command.db-restore.sh
Highlights differences in help texts for DB operations (single db, full db container)
=> Highlight DB dump differences in help texts

docker/scripts/ld.command.db-backup.sh, docker/scripts/ld.command.db-dump.sh, docker/scripts/ld.command.rebuild.sh
Fixes typo in datestamp builder (wrong letter in minutes)
=> Fix datestamp builder

README.md
Sometimes user might have issues when installing gem files. Added a workaround for that in README's issues section.
=> Added gem installation issue and solution

.env.example, docker/build/php/7.3/Dockerfile, docker/build/php/7.3/bash/bashrc, docker/build/php/7.3/conf.d/90-mailhog.ini, docker/build/php/7.3/conf.d/95-drupal-development.ini, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/scripts/ld.command.init.sh
Fixes #124 
* add PHP 7.3 build folder
* add PHP 7.3 as an option to init command
* sets PHP 7.3 as the default version
=> Issue 124 add php 73

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
Reset the config values order among docker-compose.yml file templates.
=> Set explicit container restart policy

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
=> Add reference to the documentation

docker/scripts/ld.command.init.sh
Disallow uppercase chars, allow underscore and hyphen inside the project name
=> Fix dev domain regex to disallow uppercase chars

docker/scripts/ld.command.containers.sh, docker/scripts/ld.command.db-backup.sh, docker/scripts/ld.command.db-dump.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh, docker/scripts/ld.functions.sh
During further ./ld init's (say, after updating local-docker) avoid re-creating a random IP address, but use the pre-set value.
=> Catch existing IP during init if set

docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh, docker/scripts/ld.functions.sh
Allow re-init with a clean state  - add option to remove docker-composer.yml and docker-sync.yml files. 
This allows end users to get the latest goodies even if they concern docker containers configuration (such as #166 )
=> Ask to remove docker yml files during reinit

docker/scripts/ld.command.init.sh
Proposed change: add composer-patches to the drupal init.
=> add composer-patches during drupal project init

.github/workflows/macos-latest--tests.yml, .github/workflows/test-init.yml, .github/workflows/ubuntu-18.04--tests.yml, .github/workflows/ubuntu-tests.yml, docker/scripts/ld.command.composer.sh, docker/scripts/ld.command.db-backup.sh, docker/scripts/ld.command.db-dump.sh, docker/scripts/ld.command.db-import.sh, docker/scripts/ld.command.db-restore.sh, docker/scripts/ld.command.drupal-files-folder-perms.sh, docker/scripts/ld.command.drupal-structure-fix.sh, docker/scripts/ld.command.drush.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.phpcbf.sh, docker/scripts/ld.command.phpcs.sh, docker/scripts/ld.command.run-tests.sh, docker/scripts/ld.command.up.sh, docker/scripts/ld.command.xdebug.sh
Initial setup for CI tests in Github. 
Ensure installation works, with the default values assumed in init process.
=> Add CI jobs

README.md
Issue #148 
- Make clearer distinction between the setup for initialized and non-initialized projects.
=> #148: Distinguish between non-initialized and initialized projects in the README.

.github/workflows/macos-latest--tests.yml, .github/workflows/ubuntu-18.04--tests.yml, docker/scripts/ld.command.git-repo-massage.sh, docker/scripts/ld.command.init.sh, docker/scripts/release.sh, git-hooks/pre-commit.sh, ld.sh
Replacing possibly offensive words and following the recent default branch renaming from `master` to `main`.
=> Issue 193 rewording codebase
