docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, ld.sh
Fixes issue #6 
with this change `comopser` container executes `composer install` only when `composer.lock` file exists. In the essence check prevents `composer` container to run in parallel when `./ld init` creates the codebase (`composer create-project ...`)
=> Run composer install only if .lock exists

docker/scripts/ld.command.composer.sh, docker/scripts/ld.command.drush.sh, docker/scripts/ld.command.dump.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh, docker/scripts/ld.command.restore.sh, docker/scripts/ld.command.up.sh, docker/scripts/ld.functions.sh, ld.sh
Fixes #46 
Init consumes 1st sub-command parameter as project type, and fails if it does not match file templates.
Init also writes some commonly used parameters now to `.env` file (adds or replaces existing value).
=> Issue 46 make project structure init parameter

.env.example, README.md, docker/scripts/ld.command.configure-network-down.sh, docker/scripts/ld.command.configure-network.sh, docker/scripts/ld.command.down.sh, docker/scripts/ld.command.dump.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.up.sh
Fixes #45 
This PR adds network configuration tools to `./ld`, and configures IP addresses for projects. Used IP address space is `127.0.0.0/16`, random IP address. 
In the essence binding Docker's exposed ports to a non localhost -IP allows users to run projects in parallel, for example one webserver in `127.0.100.10:80` and another in `127.0.55.66:80`
=> Issue 45 parallel projects separate by

docker/scripts/ld.functions.sh
This fixes the happily dying `./ld` if `.env` file is not present.
=> Return value instead of exiting if .env not there

.env.example, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
Environment variable introduced in .env.example controls what build file path is used with PHP containers (php, composer).
`PROJECT_PHP_VERSION=7.1|7.2`
(Note: PHP_VERSION would override the regular version variable by PHP itself.)
=> Issue 52: Make PHP version behind env variable

.env.example, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/scripts/ld.command.xdebug.sh, docker/scripts/ld.functions.sh
Fixes #53
Add Xdebug toggler command. Improve environment variable changes - when edited refresh what ever is in `.env` -file.
`./ld xdebug` reads what is xdebug status
`./ld xdebug 1|0` sets the value
=> Issue 53 toggle xdebug via command

docker/scripts/ld.command.restore.sh, docker/scripts/ld.functions.sh
Fixes #39 
Add optional filename -argumetn to restore command. File still must be inside `$DATABASE_DUMP_STORAGE` -folder (`db_dump` by default).
=> Issue 39 add filepath argument to restore command

docker/scripts/ld.command.drupal-files-folder-perms.sh
Container files are owned gby root, but php runs (and needs to be able
to create+modify files) as www-data. Tests will be run as www-data.
This allows shell actions (as root) and php process modify files equally
inside sites-folder.
Fixes #69
=> Issue #69: Adjust sites-folder perms

.env.example, docker/scripts/ld.command.init.sh
on `./ld init` configure also DRUSH_OPTIONS_URI value in `.env` file.
=> Issue 68: Add Drush default URI to .env

.env.example, docker/scripts/ld.command.run-tests.sh, docker/scripts/ld.functions.sh, ld.sh
- move .env / .env.example file checks and handling to functions
- add os-version detector function
- fix `./ld run-tests` -command, was missign `--url` -parameter pointing to Nginx container (to NOT use `localhost`, which simply does not work in containers)
=> Move functionality to functions

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
As treafik reads host-side docker container configuration all traefik routes must have a unique name across the host.
=> Prefix traefik routers with project name to avoid cross-project issues

docker/scripts/ld.command.init.sh
Fix bug in regex in init command which failed to pass sane project names and/or local domains. Also fix local domain setter that fixes `$LOCAL_DOMAIN` in `.env`
=> Fix init command and regex checks

docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh, docker/scripts/ld.functions.sh, ld.sh
* Read return value and exit if .env file operation failed
* Ask volume name before jumping into slower step
* Pass return value to indicate sucess of var replacing
* Change separator to not break replacing URLs with schmema
* Clean up init output, remove unnecessary questions
* Make .env file copy less verbose, remove checks
=> Simplify init process

docker/scripts/ld.command.self-update.sh, ld.sh
* Issue 81: Copy all files, explain what has been copied
* Issue 81: Handle dynamic tar file folder naming
* Issue 81: Use tags for updates, default to the latest tag available
* Issue 81: Use correct URL to access data
* fixup! Issue 81: Allow use of latest release and erify tag exists before use
* fixup! Issue 81: Allow use of latest release and erify tag exists before use
* Issue 81: Make curl hide progress w/ -s flag
* Issue 81: Allow use of latest release and erify tag exists before use
* Issue 81: Allow self-update on uninitialized project
=> Issue 81 better release handling for self update

.env.example, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
Fixes issue #77 
Add env variables to both `composer` and `nodejs` containers, which are checked on bootup. If set to empty or anything other but `"1"` contaners will simply exit.
=> Issue 77: Set env variables to *enable* composer and nodejs containers

docker/scripts/release.sh
Corrected the typos I could spot in the new release script file.
=> Correct typos in release script

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/docker-sync.common.yml, docker/docker-sync.skeleton.yml, docker/scripts/ld.command.db-backup.sh, docker/scripts/ld.command.db-dump.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh, docker/scripts/ld.functions.sh
Remove all :delegated -volumes, and use the regular volume (:cached) with docker-sync. 
Move all db_dump -containers to use nfs-share, and start+stop of docker-sync when running database backups (now when the db volume does not use docker-sync anymore)
=> Use nfs for low urgency filesyncing

README.md, docker/scripts/ld.command.self-update.sh, docker/scripts/self-update.sh
- Added info to README how to update the local-docker itself
- Update self-update -command info (even if not used)
- Whitespace + indenting, minor UI text updates
- use **releases**, not tags
- Use latest release or a release with a given name
=> Issue 118 self updater release tag check fix

.env.example, .gitignore, db_dumps/.gitignore, docker/build/php/7.1/conf.d/95-drupal-development.ini, docker/build/php/7.2/conf.d/95-drupal-development.ini, docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
Fix project's PHP .ini file notation to utilize .env -file configuration (notation with default value `${VAR:-DEFAULT}`does not work, but `${VAR}` does).
As a side effect we do not need the `services.php.environment` -values anymore, since all currently set vars are used via .ini file(s).
Includes also small fix to db_dumps folder's .gitignore -file, to ignore db dump files introduced in #96 
Fixes #116
=> Issue 116 fix env var expansion for php vars

docker/build/nginx/conf.d/default.conf
Increases accepted post file size to 500M in `nginx` (`php` builds do have the same value)
=> Increase upload file size limit w/ nginx

docker/scripts/ld.command.db-import.sh
Fixes command ./ld db-import [drupal] [path-to-file] being un-executable due to broken variable substitution
=> Fix "bad substitution" in db-import -script

docker/scripts/ld.command.init.sh
Fixes #132 
Install Drush and Drupal console when using the official project templates by Drupal.org. Tag Drupal core versions to 8.8.x too (not by default to 8.9.x or even 9.0.x
=> Issue 132 install drush drupal console with templates

ld.sh
Changes:
1. Issue "command hook missing" only when the function does not exits.
2. Issue a separate error message when the command returns with a nonzero exit status, suggesting to check out the command output for possible causes or suggestions on how to proceed or fix the issue.
=> 137: Issue separate warnings for command failure and command hook not existing in ld.sh

README.md, docker/build/php/7.3/Dockerfile
Fixes #139 
Using newer version of php-drupal -container, which should solve the issue.
=> Issue 139 fix missing composer binary

README.md, docker/scripts/ld.functions.sh, docker/scripts/self-update.sh
Update either `README.md` (if the newly added tag is still in the file) or overwrite the `README.local-docker.md`.
This PR breaks the updater, so the update script must be run twice to run without errors.
=> Update also README{.md,.local-docker.md} with the updater

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
Fixes Mailhog UI not being accessible. Traefik did not do port-forwading to a correct port, thus explicitly setting the correct UI port here.
=> Add loadbalancer port forwarding to Mailhog labels

docker/scripts/ld.command.phpcbf.sh, docker/scripts/ld.command.phpcs.sh
The command offers a new extended_help function as well. This can be
utilized when the 'instruct' command PR has been merged.
Note that I am leaving phpcbf out of the scope of this PR on purpose, it is not an unintended omission. I have not had very good results trying to use phpcbf myself, hence the decision.
Example usage: 
```
$ ./ld phpcs --standard=Drupal /var/www/web/themes/custom/mytheme/mytheme.theme
Next: docker-compose exec php /var/www/vendor/bin/phpcs --standard=Drupal /var/www/web/themes/custom/mytheme/mytheme.theme
FILE: /var/www/web/themes/custom/mytheme/mytheme.theme
----------------------------------------------------------------------
FOUND 12 ERRORS AFFECTING 10 LINES
----------------------------------------------------------------------
8 | ERROR | [x] Line indented …
```
=> Add phpcs command

docker/docker-compose.common.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/scripts/ld.command.configure-network.sh
Correnct faulty nginx router rules fro Traefik (only one Host() rule works), and gather all configured router hostnames even if set in the same line.
=> Configure domains per traefik labels

docker/scripts/ld.command.configure-network.sh
Make entries pushed to /etc/hosts file slightly more distinctive and clearly state the project location
=> Make hosts file notation slithgly clearer

README.md, docker/docker-compose.cached.yml, docker/docker-compose.common.yml, docker/docker-compose.ddev.yml, docker/docker-compose.skeleton.yml, docker/scripts/ld.command.init.sh, docker/scripts/ld.functions.sh, ld.sh
This PR makes init -command to check the template name (against the existing docker-compose file tempaltes present), and removes NFS from common & skeleton -templates (in favor of slower yet much more robust native `./local-dir:/container-dir:cached` volume mounts)
=> Add cached sync strategy

docker/docker-compose.cached.yml, docker/docker-compose.common.yml, docker/docker-compose.ddev.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
Change Node base image to the official Node container.
Watching docker-compose logs displays the process (both installation of `npm install` and the `gulp watch` when it starts watching and compiling.
=> Better node container for gulp watcher

.env.example, docker/docker--composer-only.yml, docker/docker-compose.cached.yml, docker/docker-compose.common.yml, docker/docker-compose.ddev.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/docker-sync.common.yml, docker/docker-sync.skeleton.yml, docker/scripts/ld.command.configure-network-down.sh, docker/scripts/ld.command.configure-network.sh, docker/scripts/ld.command.drupal-structure-fix.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.rename-volumes.sh
Fixes #127 
Moves codebase building into init-time-only -container (composer), with no other volumes than slowish :cached mount to allow composer to start with an empty root folder. 
Removes composer -container form all the development stacks (docker-compose templates). 
Makes ./ld init more robust, respecting verbosity, too.
With this PR files touched inside  `web/sites/*/files` folder are not *synced* but transferred via the regular mount. This should speed up the start of each project tremendously, since the gigabytes of files inside the files -folder are not *synced* and need no comparing by docker-sync. 
This will, however, slow reading of some PHP files, namely compiled twig files (`files/php/twig/*`), but compared to the saved time during boot up it should not be a big issue.
=> Issue 127 move drupal sites xx files folders out of docker sync

docker/docker-compose.cached.yml, docker/docker-compose.common.yml, docker/docker-compose.ddev.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml
The '[[' is a bashism and never worked when invoking 'sh -c' on the
nodejs container. That is why the CONTAINER_NODEJS_START environment
variable never seemed to have any effect.
Another issue that I can immediately think of is that at least it should be documented that the default setup runs `npm install bootstrap-sass` which may very well not be what we want, at least not in Exovify use. I have not touched that here (yet) though.
=> Fix nodejs container's test ('[') commands to work on non-bash shells

docker/scripts/ld.command.xdebug.sh, docker/scripts/ld.functions.sh
Avoid writing Xdebug toggling values to .env to avoid unnecessary "dirty" state in project environment file.
Rather, allow variable value change to be targeted to .env.local. 
Note: this measn that once the value is present in the .env.local file, it WILL override any values present in the ./.env. Any ideas how to notify user about that are welcome.
=> Write xdebug status variables on toggle to local env file

.env.example, docker/docker-sync.common.yml, docker/docker-sync.skeleton.yml, docker/scripts/ld.command.drupal-files-folder-perms.sh
Make the bootup of local faster by chown'ing less files: Map the main sync folders with www-data's UID, and do the drupal-files-folder-fix faster by skipping _files_ - we really rarely need to remove them anyway (if ever). Folder ownership inside Drupal's `sites/XX/files` is probably enough.
=> Speed up local bootup

README.md, docker/docker-compose.cached.yml, docker/docker-compose.common.yml, docker/docker-compose.ddev.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/scripts/ld.command.init.sh, docker/scripts/ld.command.tls-cert-check.sh, docker/scripts/ld.command.tls-cert.sh, ld.sh
Add SSL/TLS cert creation to init step. Adjust docker-compose file templates and Traefik configuration to handle certs and HTTPS connections. Terminate all connections in Treafik and pass on decrypted requests.
=> Add https to local

README.md
This improves README on how to install Ruby gem we need. 
Installing Gems with `sudo` is discouraged (for security reasons) and the changes are in line with that recommendation.
=> Improve README on how to install docker-sync

docker/scripts/ld.command.init.sh
Current Drupal template for 8.8 pulls latest commit form branch 8.8.x
Adding the regular release to the list of suggested projects to install.
=> Add non-dev version of Drupal 8.8 to project options

docker/scripts/release.sh
MAJOR.MINOR.PATCH, earlier also MAJOR.MINOR was accepted. No more.
=> Force use of semantic version in releases

docker/scripts/ld.command.phpcbf.sh, docker/scripts/ld.command.phpcs.sh
I discovered that both commands need explicit extension lists to
function correctly.
Without the extension list the file list the tool builds will only
contain files with the extension .php.
=> Improve documentation of phpcf and phpcbf commands

docker/scripts/ld.command.init.sh
Add Drupal 8.9 and Drupal 9.0 as options for `./ld init` initiated composer templates.
Remove unsupported Drupal 8.7 from the same list.
=> Drupal template updates to match current releases

README.md
This PR adds instructions how to set up sudoers file in a way that local-docker is allowed to auto-configure both `/etc/hosts` file with IP addresses starting 127.0.*, and similarly set and remove loopback interface aliaes to point to local domain IP addresses (to route requests to the local-docker container stack).
=> Add instructions to allow configurations w/o password

docker/docker-sync.common.yml, docker/docker-sync.skeleton.yml
The change is pretty well described in the comment but here goes once more.
This change adds an exclusion pattern in the docker-sync configuration to exclude a specific directory from docker-sync. The directory is called `pattern-lab` and it is the directory where the Pattern Lab component of Drupal themes such as Emulsify generate their static sites when either `gulp build` or `npm start` is used.
Especially with `npm start`, which starts a watcher on local, the changes to the `pattern-lab` directory are so frequent that the unison process can't keep up and docker-sync grinds to a halt.
=> Improve docker sync regarding themes

README.md, docker/scripts/ld.command.git-repo-massage.sh, docker/scripts/ld.command.init.sh, docker/scripts/ld.functions.sh, git-hooks/pre-commit.sh, ld.sh
Adding git-repo-massage -command and it using in during `./ld init` to reset the Git history (flatten to a single command).
The command checks we are on a different Git repo (not Exove/local-docker), and that the commit history does not have the know first commit of local-docker.
In other words; it does wipe your existing project master.
=> 131 add git repo massager

README.md
With these instructions users should be able to set up a shell function (alias) which will find the nearest ld.sh, execute it with all provided parameters and return the return code it received. 
If no ld.sh is found, then user is notified.
=> Add instructions to set up ld alias

.env.example, docker/scripts/ld.command.composer.sh
It would be feasible also to document adding the environment variable in `.env.local` for example on a per-need basis, but in practice using composer to do anything other than `install` almost always makes it run out of memory, especially on 1.x versions.
That's why I'm offering this simple solution of passing the `COMPOSER_MEMORY_LIMIT=-1` environment variable all the time when running composer commands.
=> Remove memory limit always when running composer

.env.example, README.md, docker/build/php/7.3/Dockerfile, docker/build/php/7.3/bash/bashrc, docker/build/php/7.4/Dockerfile, docker/build/php/7.4/bash/bashrc, docker/build/php/7.4/conf.d/90-mailhog.ini, docker/build/php/7.4/conf.d/95-drupal-development.ini, docker/docker--composer-only.yml, docker/docker-compose.cached.yml, docker/docker-compose.common.yml, docker/docker-compose.ddev.yml, docker/docker-compose.nfs.yml, docker/docker-compose.skeleton.yml, docker/scripts/ld.command.init.sh
Add PHP 7.4 via new base image for `php` container.
Update PHP 7.3 base image. 
This updates (via base image) Xdebug to 3.x, too.
Both updates bring also Drush launcher into the `php` container.
- Update PHP 7.3 base to newer image
- Add PHP 7.4 image
- Minor text fixes
- Make PHP 7.4 the default version
=> Add PHP 7.4, update PHP 7.3
